#auto-assign reviewers for created PR
name: Auto-Assign-Reviewers

on: pull_request

jobs:
  add-reviewers:
    runs-on: ubuntu-latest

    steps:
    - name: Auto Assign Action
      uses: kentaro-m/auto-assign-action@v1.1.0
      with:
        configuration-path: ".github/auto_assign.yml"
      #env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
